### Силантьева Ольга Сергеевна Т120-101М-20

In [55]:
import numpy as np

**1. Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением**

In [56]:
A = np.arange(1,6)
print(A)
B = np.arange(0)
print(B)
for i in range(A.size-1):
    B = np.append(B,A[i])
    B = np.append(B,[0,0,0])
B

[1 2 3 4 5]
[]


array([1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0])

**2. Поменять 2 строки в матрице**

In [57]:
A = np.arange(12).reshape(-1,3)
str = A[0].copy()
A[0] = A[1]
A[1] = str

A

array([[ 3,  4,  5],
       [ 0,  1,  2],
       [ 6,  7,  8],
       [ 9, 10, 11]])

**3. Рассмотрим набор из 10 троек, описывающих 10 треугольников (с общими вершинами), найти множество уникальных отрезков, составляющих все треугольники**

In [58]:
A = np.random.randint(100,size = (10,3))
print(A)
A = A.repeat(2,axis = 1)
print(A)
B = np.concatenate([A[:,1:],A[:,0:1]], axis = 1)
B = B.reshape(-1,2)
np.unique(B,axis = 0)

[[23 25 51]
 [70 48 21]
 [87 36 55]
 [16 34 60]
 [23 46 74]
 [61 75 84]
 [37 73 62]
 [72 73  3]
 [79 24 99]
 [40  1 46]]
[[23 23 25 25 51 51]
 [70 70 48 48 21 21]
 [87 87 36 36 55 55]
 [16 16 34 34 60 60]
 [23 23 46 46 74 74]
 [61 61 75 75 84 84]
 [37 37 73 73 62 62]
 [72 72 73 73  3  3]
 [79 79 24 24 99 99]
 [40 40  1  1 46 46]]


array([[ 1, 46],
       [ 3, 72],
       [16, 34],
       [21, 70],
       [23, 25],
       [23, 46],
       [24, 99],
       [25, 51],
       [34, 60],
       [36, 55],
       [37, 73],
       [40,  1],
       [46, 40],
       [46, 74],
       [48, 21],
       [51, 23],
       [55, 87],
       [60, 16],
       [61, 75],
       [62, 37],
       [70, 48],
       [72, 73],
       [73,  3],
       [73, 62],
       [74, 23],
       [75, 84],
       [79, 24],
       [84, 61],
       [87, 36],
       [99, 79]])

**4. Дан массив C; создать массив A, что np.bincount(A) == C**

In [59]:
C = np.array([0,3,2,0,2])
A =[]
for i in range(C.size):
    A = np.append(A, np.full(C[i], i)).astype('i4')
print(C)
print(np.bincount(A))

[0 3 2 0 2]
[0 3 2 0 2]


**5. Посчитать среднее, используя плавающее окно**

In [60]:
A = np.random.randint(20,size = (10))
print(A)
for i in range(1,A.size+1):
    n = 3
    if i-n < 0 :
        n = i
    print(np.average(A[i-n:i]) )

[19  3  4 17 16  9 13 12 15  8]
19.0
11.0
8.666666666666666
8.0
12.333333333333334
14.0
12.666666666666666
11.333333333333334
13.333333333333334
11.666666666666666


**6. Дан вектор Z, построить матрицу, первая строка которой (Z[0],Z[1],Z[2]), каждая последующая сдвинута на 1 (последняя (Z[-3],Z[-2],Z[-1]))**

In [61]:
Z = np.arange(21)
A = Z[:3].copy().reshape(1,3)
for i in range(1,4):
    A = np.concatenate([A,Z[i:i+3].reshape(1,3)], axis = 0)
    
print(A)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]]


**7. Инвертировать булево значение, или поменять знак у числового массива без создания нового**

In [62]:
A = np.random.randint(0,2,5,dtype = np.bool)
print(A)
print(~A)

Z = np.random.uniform(-10,10,5,)
print(Z)
Z[:] *=-1
print(Z)

[False False False  True False]
[ True  True  True False  True]
[ 8.84125134 -9.54264075 -0.26344539  5.23767378  1.92629303]
[-8.84125134  9.54264075  0.26344539 -5.23767378 -1.92629303]


**8. Посчитать ранг матрицы**

In [63]:
A =np.random.randint(20,size = (5,5))
np.linalg.matrix_rank(A)

5

**9. Найти наиболее частое значение в массиве**

In [64]:
A =np.random.randint(20,size = (5,5))
print(A)
np.bincount(A.flat).argmax()

[[10  6  8  0  5]
 [ 0  8 18  0 19]
 [ 7  7 14  0  6]
 [16 17  7 13 10]
 [ 6 12 15 18 17]]


0

**10. Извлечь все смежные 3x3 блоки из 10x10 матрицы**

In [65]:
from numpy.lib import stride_tricks
Z = np.arange(100).reshape(10,10)
print(Z)
n = 3
i = Z.shape[0] - (n-1)
j = Z.shape[1] - (n-1)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
[[[[ 0  1  2]
   [10 11 12]
   [20 21 22]]

  [[ 1  2  3]
   [11 12 13]
   [21 22 23]]

  [[ 2  3  4]
   [12 13 14]
   [22 23 24]]

  [[ 3  4  5]
   [13 14 15]
   [23 24 25]]

  [[ 4  5  6]
   [14 15 16]
   [24 25 26]]

  [[ 5  6  7]
   [15 16 17]
   [25 26 27]]

  [[ 6  7  8]
   [16 17 18]
   [26 27 28]]

  [[ 7  8  9]
   [17 18 19]
   [27 28 29]]]


 [[[10 11 12]
   [20 21 22]
   [30 31 32]]

  [[11 12 13]
   [21 22 23]
   [31 32 33]]

  [[12 13 14]
   [22 23 24]
   [32 33 34]]

  [[13 14 15]
   [23 24 25]
   [33 34 35]]

  [[14 15 16]
   [24 25 26]
   [34 35 36]]

  [[15 16 17]
   [25 26 27]
   [35 36 37]]

  [[16 17 18]
   [26 27 28]
   [36 37 38]]

  [[17 

**11. Рассмотрим множество матриц (n,n) и множество из p векторов (n,1). Посчитать сумму p произведений матриц (результат имеет размерность (n,1))**

In [66]:
n = 3
p = 2
#A = np.random.randint(1,3,size = (p,n,n))
A = np.arange(n*n*p).reshape(p,n,n)
B = np.arange(p*n).reshape(p,n,1)
print(A)
print(B)
X =np.zeros((n,1), dtype =int)
for i in range(p):
    X = X + np.dot(A[i,:,:],B[i,:])
print(X)  

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]
[[[0]
  [1]
  [2]]

 [[3]
  [4]
  [5]]]
[[127]
 [172]
 [217]]


**12. Дан массив 16x16, посчитать сумму по блокам 4x4**

In [67]:
A = np.arange(16*16).reshape(16,16)
for i in range(1,5):
    for j in range(1,5):
        print(A[(i-1)*4:i*4,(j-1)*4:j*4].sum())

408
472
536
600
1432
1496
1560
1624
2456
2520
2584
2648
3480
3544
3608
3672


**13. Найти n наибольших значений в массиве**

In [68]:
A = np.random.randint(100, size = (10,10))
n = 3
B = np.sort(A, axis = None)
print(B)
print(B[-n:])

[ 0  0  2  4  5  5  7 10 12 14 14 14 15 15 17 17 17 19 20 21 21 22 22 24
 24 26 28 28 28 31 32 33 34 35 36 37 38 38 39 39 39 40 41 44 44 46 46 47
 48 49 49 50 51 51 52 52 53 56 57 58 58 58 58 61 62 62 63 63 64 67 70 71
 72 75 76 77 77 77 78 78 79 79 81 82 83 83 84 84 84 85 86 86 88 89 89 90
 91 95 96 99]
[95 96 99]


**14. Построить прямое произведение массивов (все комбинации с каждым элементом)**

In [69]:
A = np.arange(1,7).reshape(2,3)
B = np.array([[6,7],[7,8]])
D = np.array([1,1])

arrays = [B,D]

for ar in arrays:
    C = []
    print(A.shape+ar.shape)
    for i in ar.flat:
        C = np.append(C,A*i)
    A = C.reshape(ar.shape+A.shape)    
    print(A.shape)
    print(A)

(2, 3, 2, 2)
(2, 2, 2, 3)
[[[[ 6. 12. 18.]
   [24. 30. 36.]]

  [[ 7. 14. 21.]
   [28. 35. 42.]]]


 [[[ 7. 14. 21.]
   [28. 35. 42.]]

  [[ 8. 16. 24.]
   [32. 40. 48.]]]]
(2, 2, 2, 3, 2)
(2, 2, 2, 2, 3)
[[[[[ 6. 12. 18.]
    [24. 30. 36.]]

   [[ 7. 14. 21.]
    [28. 35. 42.]]]


  [[[ 7. 14. 21.]
    [28. 35. 42.]]

   [[ 8. 16. 24.]
    [32. 40. 48.]]]]



 [[[[ 6. 12. 18.]
    [24. 30. 36.]]

   [[ 7. 14. 21.]
    [28. 35. 42.]]]


  [[[ 7. 14. 21.]
    [28. 35. 42.]]

   [[ 8. 16. 24.]
    [32. 40. 48.]]]]]


**15. Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B**

In [85]:
A = np.array([[2, 4, 1],[0,2,1],[0,4,3],[4,4,3],[2,0,3],[1,3,1],[3,2,1],[4,3,2]])
B = np.random.randint(5,size = (2,2))
print(B)
for row_A in A:
    if not(B[0][0] in row_A or B[0][1] in row_A):
        continue
    if B[1][0] in row_A or B[1][1] in row_A:
        print(row_A)

[[0 0]
 [2 3]]
[0 2 1]
[0 4 3]
[2 0 3]


**15. Дана 10x3 матрица, найти строки из неравных значений (например [2,2,3])**

In [107]:
A = np.random.randint(2,size = (10,3))
for row_A in A:
    for elem in row_A:
        if elem != row_A[0]:
            print(row_A)
            break       

[0 0 1]
[0 1 1]
[0 1 1]
[1 1 0]
[1 1 0]
[0 1 0]
[0 0 1]


**16. Преобразовать вектор чисел в матрицу бинарных представлений**

In [209]:
A = np.random.randint(10,size = (10,1), dtype= np.ubyte)
print(A)
print(np.unpackbits(A,axis = 1))

[[3]
 [8]
 [1]
 [3]
 [9]
 [9]
 [4]
 [0]
 [7]
 [5]]
[[0 0 0 0 0 0 1 1]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 0 0 1]
 [0 0 0 0 1 0 0 1]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 1 1]
 [0 0 0 0 0 1 0 1]]


**17. Дан двумерный массив. Найти все различные строки**

In [215]:
A = np.random.randint(2, size = (10,3))
print(A)
np.unique(A, axis = 0)

[[0 1 0]
 [0 0 0]
 [1 1 1]
 [1 1 1]
 [1 1 0]
 [1 0 1]
 [0 1 1]
 [0 0 0]
 [1 1 0]
 [0 1 0]]


array([[0, 0, 0],
       [0, 1, 0],
       [0, 1, 1],
       [1, 0, 1],
       [1, 1, 0],
       [1, 1, 1]])

**18. Даны векторы A и B, написать einsum эквиваленты функций inner, outer, sum и mul**

In [295]:
A = np.arange(10)
B = np.arange(10,20)
print(A)
print(B)

print(np.inner(A,B))
print(np.einsum('i,i', A, B))
print(np.outer(A,B))
print(np.einsum('i,j', A, B))
print(np.sum(A))
print(np.einsum('i->', A))
print(np.matmul(A,B))
print(np.einsum('i,i',A,B))

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]
735
735
[[  0   0   0   0   0   0   0   0   0   0]
 [ 10  11  12  13  14  15  16  17  18  19]
 [ 20  22  24  26  28  30  32  34  36  38]
 [ 30  33  36  39  42  45  48  51  54  57]
 [ 40  44  48  52  56  60  64  68  72  76]
 [ 50  55  60  65  70  75  80  85  90  95]
 [ 60  66  72  78  84  90  96 102 108 114]
 [ 70  77  84  91  98 105 112 119 126 133]
 [ 80  88  96 104 112 120 128 136 144 152]
 [ 90  99 108 117 126 135 144 153 162 171]]
[[  0   0   0   0   0   0   0   0   0   0]
 [ 10  11  12  13  14  15  16  17  18  19]
 [ 20  22  24  26  28  30  32  34  36  38]
 [ 30  33  36  39  42  45  48  51  54  57]
 [ 40  44  48  52  56  60  64  68  72  76]
 [ 50  55  60  65  70  75  80  85  90  95]
 [ 60  66  72  78  84  90  96 102 108 114]
 [ 70  77  84  91  98 105 112 119 126 133]
 [ 80  88  96 104 112 120 128 136 144 152]
 [ 90  99 108 117 126 135 144 153 162 171]]
45
45
735
735
